### PR TITLE
Migrate to @napi-rs/pinyin

### PR DESCRIPTION
**Pull request by Brooooooklyn**
`@napi-rs/pinyin` is faster and more modern `pinyin` alternative which use https://github.com/mozillazg/rust-pinyin under the hood.

There are some advantages vs `pinyin` library:

- Using latest pinyin data from https://github.com/mozillazg/pinyin-data
- No postinstall/node-gyp 
- 2~50x Faster

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
Tests passed in Github actions: https://github.com/ts-project-fork/limax/actions/runs/345075052

**Comment by lovell** [comment]
Thanks for the PR, looks good. Am I correct in thinking this change would drop support for 32-bit `node.exe` on Windows?

**Comment by Brooooooklyn** [comment]
> Am I correct in thinking this change would drop support for 32-bit node.exe on Windows?

Yes. support windows 32-bit is not hard, but I think it's the time to drop it now

**Comment by lovell** [comment]
Thanks, what version of N-API are these new dependencies using? https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix

**Comment by Brooooooklyn** [comment]
> what version of N-API are these new dependencies using

`version 1`. So it is supposed to be compatible with any NodeJS versions greater than `node@10.0.0`

**Comment by lovell** [comment]
Great, thanks.

How do people compile from source where binaries are not available e.g. non-x64 CPUs such as ARM? Are there instructions we can point people to?

**Comment by Brooooooklyn** [comment]
> How do people compile from source where binaries are not available e.g. non-x64 CPUs such as ARM? Are there instructions we can point people to?

hmm, I don't think this is a easy work for non rust developers to compile `Rust + N-API` source codes. Many native toolchains need to install and config need to do.

So I will provide more pre-build binaries for popular operation systems like `aarch64/armv7 linux/android` and `x86_64 freebsd` in future.

**Comment by lovell** [comment]
Oh, sorry, an inability to compile from source suggests this probably isn't ready to merge in its current state.

**Comment by Brooooooklyn** [comment]
> Oh, sorry, an inability to compile from source suggests this probably isn't ready to merge in its current state.

Ok, I will write postinstall script in `@napi-rs/pinyin` if **prebuild binary** is not available, and provide detailed documents to describe how to build this package from source.

**Comment by Brooooooklyn** [comment]
> Ok, I will write postinstall script in @napi-rs/pinyin if prebuild binary is not available, and provide detailed documents to describe how to build this package from source.

Convert this pull request to draft before its done.

**Comment by Brooooooklyn** [comment]
@lovell here is [document](https://github.com/Brooooooklyn/pinyin/wiki/Build-from-source) for ***how to build @napi-rs/pinyin from source***.

And `@napi-rs/pinyin` now support:

- android-arm64
- darwin-arm64
- darwin-x64
- linux-arm
- linux-arm64
- linux-x64
- linux-x64-musl
- win32-x64

**Comment by Brooooooklyn** [comment]
@lovell Do you think this can be merged now?

**Comment by lovell** [comment]
Thank you very much / xie xie !

**Comment by lovell** [comment]
v3.0.0 now available via npm.

**Pull request merged**
