### PR TITLE
Pass maintainCase and custom options through to speakingUrl

### LINKED ISSUE #19: Add support for maintainCase option
Hi, can you add an option parameter about `maintainCase` when calling `speakingurl`? for some reason, need it. thanks :)

### PR DESCRIPTION
**Pull request by lumaxis**
Fixes #19

### CODE REVIEW

**Comment by lovell** [comment]
Danke schön Lukas, I'll get the published to npm as v1.5.0 shortly.

(I'll assume @YiMysty and your good self are in cahoots.)

**Comment by lumaxis** [comment]
@lovell That's an untenable insinuation! 😉 We're evaluating this library to be used in [Visual Studio Mobile Center](https://www.visualstudio.com/vs/mobile-center/) and these configs come in very handy 😊

**Comment by lovell** [comment]
v1.5.0 now available

**Comment by lumaxis** [comment]
Thank you @lovell for the quick turnaround! 🎉

**Pull request merged**
