### PR TITLE
Fix regex that incorrectly splits numbers

### LINKED ISSUE #12: Number slugs
I've realised that slugs involving numbers behave a little weirdly.

```
> limax('12')
'12'

> limax('123')
'1-2-3'

> limax('12345')
'1-234-5'
```

Is this the intended behavior and if so, why?
Thanks!

### PR DESCRIPTION
**Pull request by dvrylc**
Resolves #12

### CODE REVIEW

**Comment by lovell** [comment]
Thanks for the PR. I think the logic needs to be `NOT (digit OR whitespace)` which would be closer to the (untested) `[^0-9\s]`. Are you able to add a couple of test cases also?

**Comment by dvrylc** [comment]
That makes sense, I've updated the regex and added tests cases to ensure - 

- Numbers don't get split
- Whitespace followed by digits don't get split (`one 2three` slugs into `one-2three` instead of `one-2-three`)

**Comment by lovell** [comment]
Marvellous, thank you Daryl. I'll publish a new release with your fix shortly.

**Comment by dvrylc** [comment]
Great, thanks! 😀

**Comment by lovell** [comment]
v1.3.0 now available via npm.

**Pull request merged**
